# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sarvex Jatasra
email: sarvex.jatasra@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Random Rablings
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sarvex.github.io" # the base hostname & protocol for your site
twitter_username: sarvex
github_username:  sarvex

# Build settings
markdown: kramdown
