
title: Sarvex Jatasra
url: 'http://sarvex.github.com'
baseurl: '' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Sarvex
tagline: Neek (nerd+geek)
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: sarvex.jatsra@gmail.com
phone: +91-8860383838
website: sarvex.github.io/blog #do not add http://
linkedin: sarvex
github: sarvex
twitter: '@sarvex'

#Update all the sections by editing the files inside _includes folder.
